suites:
  rorschach_suite:
    namespace: Rorschach
    psr4_prefix: Rorschach
extensions:
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - clover
    output:
      clover: clover.xml
formatter.name: pretty
