#!/usr/bin/env php
<?php

use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\WebDriverCapabilityType;
use Facebook\WebDriver\WebDriver;
use Psr\Container\ContainerInterface as Container;
use Rorschach\CheckpointProcessor;
use Rorschach\Config;
use Rorschach\Helpers\Env;
use Rorschach\Processors\AppocularProcessor;
use Rorschach\Snapshot;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\StyleInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

require __DIR__ . '/vendor/autoload.php';

$app = new Silly\Edition\PhpDi\Application('Rorschach', '@git-version@');

$container = $app->getContainer();

$container->set(WebDriver::class, function (Config $config) {
    try {
        $capabilities = array(WebDriverCapabilityType::BROWSER_NAME => 'chrome');
        $webdriver = RemoteWebDriver::create($config->getWebdriverUrl(), $capabilities);
        return $webdriver;
    } catch (\Exception $e) {
        throw new \RuntimeException(sprintf('Could not connect to webdriver on "%s": %s', $address, $e->getMessage()));
    }}
);

$container->set(StyleInterface::class, function (InputInterface $input, OutputInterface $output) {
    return new SymfonyStyle($input, $output);
});

$container->set(CheckpointProcessor::class, function (Container $container) {
    return $container->make(AppocularProcessor::class);
});

$app->command('run [--webdriver=] [--base-url=]', function (Container $container, InputInterface $input, OutputInterface $output) {
    $container->set(InputInterface::class, $input);
    $container->set(OutputInterface::class, $output);

    // Do the snapshot.
    $container->make(Snapshot::class)->run();
});
$app->setDefaultCommand('run', true);

$app->run();
